import React from 'react';
import { makeStyles } from '@material-ui/core/styles';
import { IDescTerms, ITermsData } from './type'
import {
  Paper
} from '@material-ui/core';


const useStyles = makeStyles({
  root: {
    width: '100%',
    marginTop: '1rem',
    padding: '1rem',
    display: 'flex',
    flexDirection: 'column',

  },
  title: {
    fontSize: '1.2rem',
    fontWeight: 400,
    marginTop: '2rem',
    marginBottom: '1rem'
  },
  subContent: {
    margin: '1rem 0 1rem 1rem'
  },
  content: {
    marginTop: '1rem'
  }
})

const TermsComponent = ({ termsContent }: { termsContent: ITermsData[] }) => {
  const classes = useStyles();

  return (
    <Paper elevation={0} className={classes.root}>
      <div className="">Terms of service</div>
      <div className=""><b>Generated by</b></div>
      {termsContent.map((element: ITermsData, index: number) => <>
        <div className={classes.title}>
          {`${index + 1}. ${element.title}`}
        </div>
        <div>
          {element.desc.map((el: IDescTerms, index: number) => <>
            <div className={classes.content}>
              {`${element.desc.length > 1 ? index + 1 + '.' : ''} ${el.content}`}
            </div>
            {!!el.subContent ?
              el.subContent.map((el: string, index: number) =>
                <div className={classes.subContent}>
                  {`${index + 1 + '.'} ${el}`}
                </div>)
              : ''}
          </>)}
        </div>
      </>)}
    </Paper>
  );
}

export default TermsComponent